# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_song_is_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
    ]
