# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default=django.utils.timezone.now, max_length=500, upload_to=''),
            preserve_default=False,
        ),
    ]
