# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20170819_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
    ]
