# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_song_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default=django.utils.timezone.now, max_length=500, upload_to=''),
            preserve_default=False,
        ),
    ]
